name: Build-On-Demand-Image
 
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker image tag
        required: true
        default: latest
 
env:
  ECR_REPO_NAME: "utaf_result_webpage"
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout the code in repo
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: aws-region-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPO_NAME }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ReleaseEndTestResults/${{inputs.tag}}
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
