name: Build-On-Demand-Image
 
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker image tag
        required: true
        default: latest
 
env:
  ECR_REPO_NAME: "utaf_result_webpage"
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout the code in repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Building the docker image
        id: build-image
        run: |
          IMAGE_TAG = ${{ inputs.tag }}
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
          echo "::set-output name=image-tag::${IMAGE_TAG}"

      - name: Pushing the docker image to ECR
        run: |
          IMAGE_TAG=${{ steps.build-image.outputs.image-tag }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG

      - name: logout of ECR
        run: |
          docker logout ${{ secrets.ECR_REPOSITORY_URI }}
