name: Build-On-Demand_image

on:
    workflow_dispatch:
      inputs:
        image_name:
          description: name for the docker image
          required: true
          default: TestResultsWeb
        tag:
          description: tag for the docker image
          required: true
          default: latest
        runner:
          type: choice
          description: runner for the job
          options:
            - utaf-web-runner
            - ubuntu-latest

env:
  ECR_REPO_NAME: "utaf_result_webpage"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  job1:
    runs-on: utaf-web-runner
    steps:
      - name: Checkout the code from the repo to instance
        uses: actions/checkout@v3
      - name: Building the docker image and tagging the created image
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REPO_NAME }}:${{inputs.tag}} ResultEndTestResults/
          docker tag ${{ env.ECR_REPO_NAME }}:${{inputs.tag}} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ inputs.tag }}
      
  job2:
    runs-on: utaf-web-runner
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

  job3:
    runs-on: utaf-web-runner
    needs: [job1, job2]
    steps:
      - name: Pushing the docker Image to ECR
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ inputs.tag }}

      - name: running the docker container
        run: |
          docker run -d --name run-from-ecr-image -p 8080:8080 ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ inputs.tag }}

      - name: logout of ECR
        run: |
          docker logout ${{ secrets.ECR_REPOSITORY_URI }}
